# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Save Cash' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  use_frameworks!

  # Pods for Save Cash

  target 'Save CashTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Save CashUITests' do
    # Pods for testing
  end

end
